language: python
python:
    - "2.7"
    - "3.5"
install:
    - sudo apt-get autoremove
    - sudo apt-get update
    - sudo apt-get install python-dev python3-dev
    - sudo apt-get install python-setuptools python3-setuptools
    - sudo apt-get install python-numpy
    - sudo apt-get install zlib1g-dev
    - sudo apt-get install libhdf5-serial-dev
    - sudo apt-get install python-nose
    - sudo pip install --install-option='--no-cython-compile' cython
    - pip install .
    - pip install pillow numpy h5py requests
    - pip install coveralls
    - pip install json-spec
    - pip install simplejson regex wget
    - pip install blosc
cache:
    - pip
    - apt
    - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
script:
    - coverage run -m unittest discover
